#!/usr/bin/env python3
"""Check the group protocol test vectors, and what produced them.

The vectors in `tests/group_vectors/group_vectors_v1.json` were generated by
an encoder written from SPEC_GROUP.md, signed by a transcription of the RFC
8032 reference algorithm.  No group implementation exists yet: when one lands
(plan step 8) it is checked against this file, and the file does not move to
accommodate it.

What runs here, against the ORDINARY production wheel:

* every signature in the file verifies under the real Ed448 implementation --
  which is the cross-implementation check that matters, since the signatures
  were produced by entirely separate code;
* every value the spec defines as a hash is recomputed from the preimage the
  file records;
* the structural invariants of §§1-4 hold on the recorded bytes;
* the negative cases really are negative;
* the pure-Python signer stays quarantined in `tests/group_vectors/`.

Regenerating the file is slow (RFC 8032 in Python, affine coordinates) and is
not part of this module.  See SPEC_GROUP.md §15.
"""

import ast
import hashlib
import json
import os
import sys

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

core = pytest.importorskip("otrv4_core")

VECTOR_DIR = os.path.join(ROOT, "tests", "group_vectors")
VECTOR_FILE = os.path.join(VECTOR_DIR, "group_vectors_v1.json")

GROUP_DOMAIN = b"OTRv4Plus_Group_v1\x00"
SPEC_VERSION = 0x01


@pytest.fixture(scope="module")
def vectors():
    with open(VECTOR_FILE, encoding="utf-8") as handle:
        return json.load(handle)


def unhex(value):
    return bytes.fromhex(value)


def sha3_512(data):
    return hashlib.sha3_512(data).digest()


def verify(pub, message, signature):
    return core.verify_ed448_sig(pub, message, signature)


# ------------------------------------------------------------------ the file
class TestTheFileItself:

    def test_it_declares_what_it_is(self, vectors):
        assert vectors["vector_set_version"] == 1
        assert vectors["spec"].startswith("SPEC_GROUP.md")
        assert "not" in vectors["generated_by"].lower()
        assert "test use only" in vectors["warning"].lower()

    def test_the_constants_match_the_spec(self, vectors):
        constants = vectors["constants"]
        assert unhex(constants["GROUP_DOMAIN"]) == GROUP_DOMAIN
        assert constants["SPEC_VERSION"] == SPEC_VERSION
        assert constants["hash"] == "SHA3-512"
        assert constants["length_prefix_bytes"] == 4, (
            "four bytes, not eight -- SPEC_GROUP.md §1")
        assert constants["context_tags"] == {
            "member_entry": 1, "member_set": 2, "group_state": 3,
            "commit": 4, "proposal": 5, "vote": 6, "envelope": 7}
        assert constants["sizes"] == {
            "identity_pub": 57, "signature": 114, "digest": 64,
            "group_id": 32, "message_id": 16, "proposal_id": 16}

    def test_every_category_is_present(self, vectors):
        """The fifteen categories the plan called for, plus votes and the
        message envelope, which §7.1 and §9 also need."""
        assert set(vectors["vectors"]) == {
            "01_member_entry", "02_member_set", "03_genesis", "04_join",
            "05_leave", "06_membership_replacement", "07_state_chain",
            "08_concurrent_commits", "09_equivocation",
            "10_commit_id_determinism", "11_ed448_signatures",
            "12_invalid_signatures", "13_wrong_parent",
            "14_unauthorised_signers", "15_malformed_encodings",
            "16_complete_verification", "17_threshold_votes",
            "18_message_envelope"}

    def test_every_actor_key_derives_from_its_published_seed(self, vectors):
        """The seeds are in the file so a third party can reproduce the
        vectors without running our generator.  This checks they are the
        seeds that were actually used."""
        for name, actor in vectors["actors"].items():
            seed = unhex(actor["seed"])
            assert len(seed) == 57
            expected = hashlib.shake_256(
                b"OTRv4Plus group test vector seed v1|"
                + name.encode()).digest(57)
            assert seed == expected, "%s: seed is not the documented one" % name
            assert len(unhex(actor["identity_pub"])) == 57


# --------------------------------------------------- the signatures are real
class TestSignaturesVerifyUnderTheRealImplementation:
    """The signatures were produced by ed448_rfc8032.py, which shares no code
    with `ed448-goldilocks-plus`.  That they verify here is a genuine
    two-implementation agreement, and it needs no test-only build: verifying
    is a production API."""

    def test_raw_ed448_signature_vectors(self, vectors):
        cases = vectors["vectors"]["11_ed448_signatures"]["cases"]
        assert len(cases) >= 12
        for case in cases:
            assert verify(unhex(case["identity_pub"]),
                          unhex(case["message"]),
                          unhex(case["signature"])), case["signer"]

    def test_a_signature_does_not_verify_over_a_different_message(self,
                                                                  vectors):
        case = vectors["vectors"]["11_ed448_signatures"]["cases"][0]
        assert not verify(unhex(case["identity_pub"]),
                          unhex(case["message"]) + b"\x00",
                          unhex(case["signature"]))

    @pytest.mark.parametrize("section,body,signature,signer", [
        ("04_join", "commit_encoded", "commit_signature", None),
        ("05_leave", "commit_encoded", "commit_signature", None),
        ("06_membership_replacement", "revoke_commit_encoded",
         "revoke_commit_signature", None),
        ("06_membership_replacement", "join_commit_encoded",
         "join_commit_signature", None),
        ("17_threshold_votes", "commit_encoded", "commit_signature", None),
    ])
    def test_commit_signatures_verify(self, vectors, section, body,
                                      signature, signer):
        entry = vectors["vectors"][section]
        message = unhex(entry[body])
        # §6: the signer's key is the last field of the commit, length-
        # prefixed.  Read it back out rather than trusting a separate field.
        signer_pub = message[-57:]
        assert int.from_bytes(message[-61:-57], "big") == 57
        assert verify(signer_pub, message, unhex(entry[signature]))

    def test_concurrent_and_equivocating_commits_are_all_valid(self, vectors):
        """Both §8 cases turn on commits that are individually valid.  If
        either signature failed, the vector would be testing the wrong
        thing."""
        for section in ("08_concurrent_commits", "09_equivocation"):
            entry = vectors["vectors"][section]
            for key in ("commit_a", "commit_b"):
                message = unhex(entry[key]["encoded"])
                assert verify(message[-57:], message,
                              unhex(entry[key]["signature"]))

    def test_the_evidence_is_the_canonical_sorted_vote_records(self,
                                                               vectors):
        """§7.1.1: sorted by voter key, 329 bytes per record, no separator.
        Two members counting the same votes must produce the same bytes, or
        they produce different commit_ids for the same decision."""
        entry = vectors["vectors"]["17_threshold_votes"]
        evidence = unhex(entry["evidence"])
        assert len(evidence) % 329 == 0
        records = [evidence[i:i + 329] for i in range(0, len(evidence), 329)]
        assert len(records) == len(entry["votes"]) >= entry["votes_required"]
        voters = []
        for record in records:
            body, signature = record[:215], record[215:]
            voter = body[-57:]
            assert verify(voter, body, signature)
            voters.append(voter)
        assert voters == sorted(voters), "evidence is not in canonical order"
        assert len(set(voters)) == len(voters), "a voter counted twice"
        target = unhex(vectors["actors"][entry["revocation_target"]]
                       ["identity_pub"])
        assert target not in voters, (
            "the revocation target voted on its own revocation")

    def test_proposal_and_votes_verify(self, vectors):
        entry = vectors["vectors"]["17_threshold_votes"]
        proposal = unhex(entry["proposal_encoded"])
        assert verify(proposal[-57:], proposal,
                      unhex(entry["proposal_signature"]))
        for vote in entry["votes"]:
            body = unhex(vote["encoded"])
            assert verify(body[-57:], body, unhex(vote["signature"]))


# ----------------------------------------------------- the hashes recompute
class TestHashesRecompute:

    def test_genesis_group_id(self, vectors):
        entry = vectors["vectors"]["03_genesis"]
        preimage = unhex(entry["group_id_preimage"])
        assert preimage.startswith(GROUP_DOMAIN + bytes([SPEC_VERSION, 0x03]))
        assert sha3_512(preimage)[:32] == unhex(entry["group_id"])
        assert unhex(entry["previous_state_hash"]) == b"\x00" * 64

    def test_genesis_state_hash(self, vectors):
        entry = vectors["vectors"]["03_genesis"]
        assert sha3_512(unhex(entry["group_state_encoded"])) == unhex(
            entry["state_hash"])

    def test_state_chain_links_and_hashes(self, vectors):
        chain = vectors["vectors"]["07_state_chain"]["chain"]
        assert [link["epoch"] for link in chain] == [0, 1, 2, 3]
        previous = None
        for link in chain:
            encoded = unhex(link["group_state_encoded"])
            assert sha3_512(encoded) == unhex(link["state_hash"])
            if previous is None:
                assert unhex(link["previous_state_hash"]) == b"\x00" * 64
            else:
                assert unhex(link["previous_state_hash"]) == previous, (
                    "epoch %d does not link to its parent" % link["epoch"])
            previous = unhex(link["state_hash"])

    @pytest.mark.parametrize("section,body,signature,commit_id", [
        ("04_join", "commit_encoded", "commit_signature", "commit_id"),
        ("05_leave", "commit_encoded", "commit_signature", "commit_id"),
        ("06_membership_replacement", "revoke_commit_encoded",
         "revoke_commit_signature", "revoke_commit_id"),
        ("17_threshold_votes", "commit_encoded", "commit_signature",
         "commit_id"),
    ])
    def test_commit_id_is_the_hash_of_body_and_signature(
            self, vectors, section, body, signature, commit_id):
        entry = vectors["vectors"][section]
        assert sha3_512(unhex(entry[body]) + unhex(entry[signature])) == \
            unhex(entry[commit_id])

    def test_the_vote_binds_the_proposal_hash_not_just_its_id(self, vectors):
        entry = vectors["vectors"]["17_threshold_votes"]
        expected = sha3_512(unhex(entry["proposal_encoded"])
                            + unhex(entry["proposal_signature"]))
        assert unhex(entry["proposal_hash"]) == expected
        for vote in entry["votes"]:
            assert expected in unhex(vote["encoded"]), (
                "a vote that bound only the proposal id would let the "
                "proposer alter the proposal after votes were cast")


# ---------------------------------------------------- structural invariants
class TestStructuralInvariants:

    def test_every_encoded_structure_carries_its_context_tag(self, vectors):
        tag_for = {
            ("01_member_entry", "encoded"): 0x01,
            ("03_genesis", "group_state_encoded"): 0x03,
            ("04_join", "commit_encoded"): 0x04,
            ("05_leave", "commit_encoded"): 0x04,
            ("17_threshold_votes", "proposal_encoded"): 0x05,
        }
        for (section, field), tag in tag_for.items():
            entry = vectors["vectors"][section]
            blobs = ([case[field] for case in entry["cases"]]
                     if "cases" in entry else [entry[field]])
            for blob in blobs:
                raw = unhex(blob)
                assert raw[:len(GROUP_DOMAIN)] == GROUP_DOMAIN
                assert raw[len(GROUP_DOMAIN)] == SPEC_VERSION
                assert raw[len(GROUP_DOMAIN) + 1] == tag

    def test_member_entries_are_all_the_documented_shape(self, vectors):
        for case in vectors["vectors"]["01_member_entry"]["cases"]:
            raw = unhex(case["encoded"])
            offset = len(GROUP_DOMAIN) + 2
            assert int.from_bytes(raw[offset:offset + 4], "big") == 57
            key = raw[offset + 4:offset + 61]
            assert key == unhex(case["identity_pub"])
            offset += 61
            jid_len = int.from_bytes(raw[offset:offset + 4], "big")
            jid = raw[offset + 4:offset + 4 + jid_len]
            assert jid.decode("utf-8") == case["jid"]
            offset += 4 + jid_len
            assert raw[offset] == case["role"]
            assert int.from_bytes(raw[offset + 1:offset + 9], "big") == \
                case["joined_epoch"]
            assert offset + 9 == len(raw), "trailing bytes"

    def test_the_jid_is_not_what_orders_a_member_set(self, vectors):
        entry = vectors["vectors"]["02_member_set"]
        keys = [unhex(m["identity_pub"]) for m in entry["members"]]
        by_key = [m["name"] for m in sorted(
            entry["members"], key=lambda m: unhex(m["identity_pub"]))]
        assert entry["order_by_identity_key"] == by_key
        assert sorted(keys) == [unhex(m["identity_pub"]) for m in sorted(
            entry["members"], key=lambda m: unhex(m["identity_pub"]))]
        assert entry["order_by_identity_key"] != \
            entry["order_by_jid_do_not_use"], (
                "this vector is only meaningful if the two orders differ")

    def test_the_member_set_hash_does_not_depend_on_input_order(self,
                                                                vectors):
        entry = vectors["vectors"]["02_member_set"]
        assert entry["member_set_hash"] == \
            entry["member_set_hash_is_order_independent_input"]

    def test_the_empty_set_still_hashes_to_something_distinct(self, vectors):
        entry = vectors["vectors"]["02_member_set"]
        assert entry["empty_set_hash"] != entry["single_member_set_hash"]
        assert sha3_512(GROUP_DOMAIN + bytes([SPEC_VERSION, 0x02])
                        + (0).to_bytes(4, "big")).hex() == \
            entry["empty_set_hash"]

    def test_a_shared_jid_does_not_merge_two_devices(self, vectors):
        entry = vectors["vectors"]["06_membership_replacement"]
        assert entry["revoked_identity_pub"] != \
            entry["replacement_identity_pub"]
        assert entry["state_after_revoke"] != entry["state_after_replacement"]

    def test_the_message_envelope_has_no_signature_field(self, vectors):
        entry = vectors["vectors"]["18_message_envelope"]
        assert entry["signed"] is False
        for case in entry["cases"]:
            raw = unhex(case["encoded"])
            expected = (GROUP_DOMAIN + bytes([SPEC_VERSION, 0x07])
                        + (32).to_bytes(4, "big") + unhex(case["group_id"])
                        + case["epoch"].to_bytes(8, "big")
                        + (16).to_bytes(4, "big") + unhex(case["message_id"])
                        + (len(unhex(case["payload"]))).to_bytes(4, "big")
                        + unhex(case["payload"]))
            assert raw == expected


# ------------------------------------------------- the negatives are negative
class TestTheRejectionCasesReallyFail:

    def test_invalid_signature_cases_do_not_verify(self, vectors):
        for case in vectors["vectors"]["12_invalid_signatures"]["cases"]:
            message = unhex(case["commit_encoded"])
            signature = unhex(case["commit_signature"])
            signer_pub = message[-57:]
            assert case["expected"] == "reject"
            if len(signature) != 114:
                continue                 # cannot be passed to the verifier
            assert not verify(signer_pub, message, signature), case["name"]

    def test_the_wrong_key_case_verifies_only_under_the_wrong_key(self,
                                                                  vectors):
        """Precision: the signature is not garbage.  It is a valid signature
        by the wrong device, which is exactly what condition 5 catches."""
        cases = vectors["vectors"]["12_invalid_signatures"]["cases"]
        case = next(c for c in cases if "other than" in c["name"])
        message = unhex(case["commit_encoded"])
        mallory = unhex(vectors["actors"]["mallory"]["identity_pub"])
        assert verify(mallory, message, unhex(case["commit_signature"]))
        assert not verify(message[-57:], message,
                          unhex(case["commit_signature"]))

    def test_wrong_parent_cases_are_correctly_signed(self, vectors):
        """Every one of these must be rejected on state, not on signature --
        a verifier that rejected them for the wrong reason would pass a naive
        test while being wrong."""
        entry = vectors["vectors"]["13_wrong_parent"]
        for case in entry["cases"]:
            message = unhex(case["commit_encoded"])
            assert verify(message[-57:], message,
                          unhex(case["commit_signature"])), case["name"]
            assert case["expected"] == "reject"

    def test_unauthorised_signer_cases_are_correctly_signed(self, vectors):
        entry = vectors["vectors"]["14_unauthorised_signers"]
        for case in entry["cases"]:
            message = unhex(case["commit_encoded"])
            assert message[-57:] == unhex(case["signer_identity_pub"])
            assert verify(message[-57:], message,
                          unhex(case["commit_signature"])), case["name"]
            assert case["expected"] == "reject"

    def test_malformed_encodings_are_recorded_as_bytes(self, vectors):
        entry = vectors["vectors"]["15_malformed_encodings"]
        names = [case["name"] for case in entry["cases"]]
        assert "eight-byte length prefixes" in names
        assert "member set in descending key order" in names
        for case in entry["cases"]:
            assert case["expected"] == "reject"
            assert unhex(case["bytes"])          # parses as hex, is non-empty
            assert case["reason"]

    def test_the_eight_byte_prefix_case_really_uses_eight_bytes(self,
                                                                vectors):
        entry = vectors["vectors"]["15_malformed_encodings"]
        case = next(c for c in entry["cases"]
                    if c["name"] == "eight-byte length prefixes")
        raw = unhex(case["bytes"])
        offset = len(GROUP_DOMAIN) + 2
        assert int.from_bytes(raw[offset:offset + 8], "big") == 57
        assert int.from_bytes(raw[offset:offset + 4], "big") == 0, (
            "a four-byte reader sees a zero-length field, which is how this "
            "mistake produces silent tag failures rather than parse errors")


# ------------------------------------------------------------------- §8 rules
class TestTheConcurrencyVectorsSayTheRightThing:
    """These two sections exist to stop one specific misreading: applying the
    §8.1 tie-break to the §8.2 case."""

    def test_the_benign_case_has_two_different_signers(self, vectors):
        entry = vectors["vectors"]["08_concurrent_commits"]
        a = unhex(entry["commit_a"]["encoded"])[-57:]
        b = unhex(entry["commit_b"]["encoded"])[-57:]
        assert a != b
        assert entry["different_signers"] is True
        assert entry["expected_resolution"] == "converge"

    def test_the_benign_winner_is_the_lower_commit_id(self, vectors):
        entry = vectors["vectors"]["08_concurrent_commits"]
        ids = {"commit_a": unhex(entry["commit_a"]["commit_id"]),
               "commit_b": unhex(entry["commit_b"]["commit_id"])}
        lower = min(ids, key=lambda key: ids[key])
        assert entry["expected_winner"] == lower
        assert unhex(entry["expected_winner_commit_id"]) == ids[lower]

    def test_the_equivocation_case_has_one_signer_and_no_winner(self,
                                                                vectors):
        entry = vectors["vectors"]["09_equivocation"]
        a = unhex(entry["commit_a"]["encoded"])[-57:]
        b = unhex(entry["commit_b"]["encoded"])[-57:]
        assert a == b == unhex(entry["signer_identity_pub"])
        assert entry["same_signer"] is True
        assert entry["expected_resolution"] == "equivocation_detected"
        assert entry["expected_epoch_advance"] is False
        assert entry["expected_both_retained_as_evidence"] is True
        assert "expected_winner" not in entry, (
            "there is no winner in an equivocation; naming one would invite "
            "exactly the misreading SPEC_GROUP.md §8 forbids")

    def test_both_equivocating_commits_share_a_parent(self, vectors):
        entry = vectors["vectors"]["09_equivocation"]
        parent = unhex(entry["parent_state_hash"])
        for key in ("commit_a", "commit_b"):
            assert parent in unhex(entry[key]["encoded"])

    def test_the_two_sections_are_not_the_same_pair_of_commits(self,
                                                               vectors):
        concurrent = vectors["vectors"]["08_concurrent_commits"]
        equivocation = vectors["vectors"]["09_equivocation"]
        assert concurrent["commit_b"]["commit_id"] != \
            equivocation["commit_b"]["commit_id"]


# ------------------------------------------------------------- quarantine
class TestTheReferenceSignerStaysInItsCorner:

    def test_nothing_outside_the_vector_directory_imports_it(self):
        """`ed448_rfc8032.py` is variable-time arithmetic on secret scalars.
        It exists to generate vectors and must never be reachable from client
        code."""
        offenders = []
        for base, dirs, files in os.walk(ROOT):
            dirs[:] = [d for d in dirs
                       if d not in {".git", "target", "build", "__pycache__",
                                    "node_modules", ".venv"}]
            if os.path.abspath(base) == os.path.abspath(VECTOR_DIR):
                continue
            for name in files:
                if not name.endswith(".py"):
                    continue
                path = os.path.join(base, name)
                if os.path.abspath(path) == os.path.abspath(__file__):
                    continue
                with open(path, encoding="utf-8", errors="replace") as handle:
                    if "ed448_rfc8032" in handle.read():
                        offenders.append(os.path.relpath(path, ROOT))
        assert not offenders, (
            "the reference Ed448 signer is imported outside "
            "tests/group_vectors/: %s" % offenders)

    def test_it_says_it_is_not_for_production(self):
        path = os.path.join(VECTOR_DIR, "ed448_rfc8032.py")
        with open(path, encoding="utf-8") as handle:
            source = handle.read()
        assert "NOT FOR PRODUCTION USE" in source
        assert "variable-time" in source
        ast.parse(source)

    def test_the_generator_does_not_import_the_client(self):
        """SPEC_GROUP.md §15.2: vectors must not be produced by the code they
        check.  The generator may import the RFC signer and the standard
        library, and nothing else from this repository."""
        path = os.path.join(VECTOR_DIR, "generate_group_vectors.py")
        with open(path, encoding="utf-8") as handle:
            tree = ast.parse(handle.read())
        imported = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                imported.update(alias.name.split(".")[0]
                                for alias in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                imported.add(node.module.split(".")[0])
        assert imported <= {"hashlib", "json", "os", "sys", "ed448_rfc8032"}, (
            "the generator imported something it must not: %s" % imported)
        assert "otrv4_core" not in imported
