#!/usr/bin/env python3
"""Ed448 (RFC 8032) in pure Python, for generating protocol test vectors.

WHY THIS FILE EXISTS
====================
Test vectors produced by the implementation they are meant to check prove only
that the implementation agrees with itself.  That is the exact defect
GROUP_CRYPTO_AUDIT.md §2 found in the old ML-KEM tests, and SPEC_GROUP.md §15.2
forbids repeating it.

So the group vectors are generated by an encoder written from SPEC_GROUP.md,
and the signatures in them are produced by *this* file: a transcription of the
RFC 8032 reference algorithm that shares no code with `otrv4_core`, with
`ed448-goldilocks-plus`, or with anything else in this repository.

It is deliberately naive -- affine coordinates, a modular inverse per point
addition.  A few hundred signatures take a few seconds, which is all that is
ever asked of it.

NOT FOR PRODUCTION USE
======================
This is variable-time arithmetic on secret scalars.  It leaks through timing
and must never be imported by client code.  Nothing outside
`tests/group_vectors/` may import it; `tests/test_group_vectors.py` enforces
that.  Production signing is `Ed448KeyHandle.sign()`, where the key is
Rust-owned and never becomes a Python object.

Self-check: `python3 ed448_rfc8032.py` verifies the RFC 8032 §7.4 vectors.
"""

import hashlib

# ---------------------------------------------------------------- parameters
# RFC 8032 §5.2.  edwards448: x^2 + y^2 = 1 + d x^2 y^2 over GF(p).
P = 2**448 - 2**224 - 1
D = -39081 % P
L = (2**446
     - 13818066809895115352007386748515426880336692474882178609894547503885)
B_X = int("224580040295924300187604334099896036246789641632564134246125461"
          "686950415467406032909029192869357953282578032075146446173674602"
          "635247710")
B_Y = int("298819210078481492676017930443930673437544040154080242095928241"
          "372331506189835876003536878655418784733982303233503462500531545"
          "062832660")
KEY_LEN = 57          # b/8, with b = 456
SIG_LEN = 114         # 2b/8
HASH_LEN = 114


def _shake256(data: bytes, length: int = HASH_LEN) -> bytes:
    return hashlib.shake_256(data).digest(length)


def _dom4(phflag: int, context: bytes) -> bytes:
    """RFC 8032 §5.2.1.  Ed448 always prefixes; there is no "pure vs prefixed"
    choice as there is for Ed25519."""
    if len(context) > 255:
        raise ValueError("Ed448 context is limited to 255 bytes")
    return b"SigEd448" + bytes([phflag, len(context)]) + context


def _inv(x: int) -> int:
    return pow(x, P - 2, P)


# ------------------------------------------------------------------- points
# Affine (x, y).  The identity is (0, 1).

def _add(p1, p2):
    x1, y1 = p1
    x2, y2 = p2
    t = D * x1 * x2 % P * y1 % P * y2 % P
    x3 = (x1 * y2 + x2 * y1) % P * _inv(1 + t) % P
    y3 = (y1 * y2 - x1 * x2) % P * _inv(1 - t) % P
    return (x3, y3)


def _mul(point, scalar: int):
    result = (0, 1)
    addend = point
    while scalar:
        if scalar & 1:
            result = _add(result, addend)
        addend = _add(addend, addend)
        scalar >>= 1
    return result


def _encode_point(point) -> bytes:
    x, y = point
    out = bytearray(y.to_bytes(KEY_LEN, "little"))
    out[56] |= (x & 1) << 7          # sign bit in the spare top bit
    return bytes(out)


def _decode_point(data: bytes):
    """Returns None for a non-canonical or off-curve encoding, which callers
    must treat as an invalid signature rather than an exception."""
    if len(data) != KEY_LEN:
        return None
    sign = data[56] >> 7
    y = int.from_bytes(bytes(data[:56]) + bytes([data[56] & 0x7F]), "little")
    if y >= P:
        return None
    # x^2 = (y^2 - 1) / (d y^2 - 1)
    numerator = (y * y - 1) % P
    denominator = (D * y % P * y - 1) % P
    if denominator == 0:
        return None
    x_squared = numerator * _inv(denominator) % P
    if x_squared == 0:
        if sign:
            return None                     # -0 is not a valid encoding
        return (0, y)
    x = pow(x_squared, (P + 1) // 4, P)     # p == 3 (mod 4)
    if x * x % P != x_squared:
        return None                         # not a square: off the curve
    if x & 1 != sign:
        x = (-x) % P
    return (x, y)


# ------------------------------------------------------------------ the API

def _expand(seed: bytes):
    if len(seed) != KEY_LEN:
        raise ValueError("Ed448 seed must be %d bytes" % KEY_LEN)
    digest = bytearray(_shake256(seed))
    clamped = digest[:KEY_LEN]
    clamped[0] &= 0xFC          # clear the two low bits
    clamped[55] |= 0x80         # set the high bit of the second-to-last octet
    clamped[56] = 0x00          # clear the last octet entirely
    scalar = int.from_bytes(bytes(clamped), "little")
    prefix = bytes(digest[KEY_LEN:])
    return scalar, prefix


def public_key(seed: bytes) -> bytes:
    scalar, _prefix = _expand(seed)
    return _encode_point(_mul((B_X, B_Y), scalar))


def sign(seed: bytes, message: bytes, context: bytes = b"") -> bytes:
    scalar, prefix = _expand(seed)
    encoded_a = _encode_point(_mul((B_X, B_Y), scalar))
    dom = _dom4(0, context)
    r = int.from_bytes(_shake256(dom + prefix + message), "little") % L
    encoded_r = _encode_point(_mul((B_X, B_Y), r))
    k = int.from_bytes(
        _shake256(dom + encoded_r + encoded_a + message), "little") % L
    s = (r + k * scalar) % L
    return encoded_r + s.to_bytes(KEY_LEN, "little")


def verify(pub: bytes, message: bytes, signature: bytes,
           context: bytes = b"") -> bool:
    if len(signature) != SIG_LEN or len(pub) != KEY_LEN:
        return False
    point_a = _decode_point(pub)
    point_r = _decode_point(signature[:KEY_LEN])
    if point_a is None or point_r is None:
        return False
    s = int.from_bytes(signature[KEY_LEN:], "little")
    if s >= L:
        return False
    k = int.from_bytes(
        _shake256(_dom4(0, context) + signature[:KEY_LEN] + pub + message),
        "little") % L
    left = _mul((B_X, B_Y), s)
    right = _add(point_r, _mul(point_a, k))
    # Cofactor 4: compare 4*[s]B with 4*(R + [k]A), as RFC 8032 permits.
    for _ in range(2):
        left = _add(left, left)
        right = _add(right, right)
    return left == right


# ------------------------------------------------------- RFC 8032 self-check
# §7.4.  If these fail, nothing generated by this file means anything.
RFC_8032_VECTORS = [
    {
        "name": "Blank",
        "seed": "6c82a562cb808d10d632be89c8513ebf6c929f34ddfa8c9f63c9960ef6"
                "e348a3528c8a3fcc2f044e39a3fc5b94492f8f032e7549a20098f95b",
        "public": "5fd7449b59b461fd2ce787ec616ad46a1da1342485a70e1f8a0ea75d8"
                  "0e96778edf124769b46c7061bd6783df1e50f6cd1fa1abeafe8256180",
        "message": "",
        "signature":
            "533a37f6bbe457251f023c0d88f976ae2dfb504a843e34d2074fd823d41a59"
            "1f2b233f034f628281f2fd7a22ddd47d7828c59bd0a21bfd3980ff0d2028d4"
            "b18a9df63e006c5d1c2d345b925d8dc00b4104852db99ac5c7cdda8530a113"
            "a0f4dbb61149f05a7363268c71d95808ff2e652600",
    },
    {
        # Key derivation only.  The signature from this RFC entry is
        # deliberately absent: it could not be transcribed with certainty from
        # an offline copy, and a test vector nobody can vouch for is worse than
        # no test vector.  Seed and public key are anchored -- deriving this
        # public key from this seed cannot succeed by accident.
        "name": "1 octet",
        "seed": "c4eab05d357007c632f3dbb48489924d552b08fe0c353a0d4a1f00acda"
                "2c463afbea67c5e8d2877c5e3bc397a659949ef8021e954e0a12274e",
        "public": "43ba28f430cdff456ae531545f7ecd0ac834a55d9358c0372bfa0c6c"
                  "6798c0866aea01eb00742802b8438ea4cb82169c235160627b4c3a94"
                  "80",
    },
]


def cross_check_against_core() -> str:
    """Agree with `ed448-goldilocks-plus` through the gated core, if present.

    One exact RFC vector proves the algorithm; agreeing with a completely
    separate implementation over random seeds proves it did not get lucky.
    Needs the test-only build (SPEC_GROUP.md §15.1) because production has no
    way to fix a signing key -- returns a reason string when it cannot run.
    """
    try:
        import otrv4_core
    except ImportError:
        return "otrv4_core is not installed"
    if not hasattr(otrv4_core.Ed448KeyHandle, "from_seed_bytes"):
        return ("the installed core is a production build: no from_seed_bytes "
                "(this is the correct state for a release; rebuild with "
                "OTRV4PLUS_ALLOW_TEST_GATES=1 --features test-only-kdf to "
                "cross-check)")
    for index in range(8):
        seed = bytes((index * 37 + position) % 256 for position in range(57))
        message = b"cross-check message %d" % index
        handle = otrv4_core.Ed448KeyHandle.from_seed_bytes(seed)
        if bytes(handle.public_bytes()) != public_key(seed):
            raise AssertionError(
                "public key disagreement with otrv4_core at seed %d" % index)
        theirs = bytes(handle.sign(message))
        ours = sign(seed, message)
        if theirs != ours:
            raise AssertionError(
                "signature disagreement with otrv4_core at seed %d\n"
                "  core: %s\n  rfc : %s" % (index, theirs.hex(), ours.hex()))
        if not verify(public_key(seed), message, theirs):
            raise AssertionError("core signature failed RFC 8032 verification")
    return ""


def _self_check() -> None:
    for vector in RFC_8032_VECTORS:
        seed = bytes.fromhex(vector["seed"])
        message = bytes.fromhex(vector.get("message", ""))
        expected_pub = bytes.fromhex(vector["public"])
        got_pub = public_key(seed)
        assert got_pub == expected_pub, (
            "%s: public key mismatch\n  got %s\n  want %s"
            % (vector["name"], got_pub.hex(), expected_pub.hex()))
        if "signature" not in vector:
            print("RFC 8032 §7.4 %-8s ok (public key only)" % vector["name"])
            continue
        expected_sig = bytes.fromhex(vector["signature"])
        got_sig = sign(seed, message)
        assert got_sig == expected_sig, (
            "%s: signature mismatch\n  got %s\n  want %s"
            % (vector["name"], got_sig.hex(), expected_sig.hex()))
        assert verify(expected_pub, message, expected_sig)
        assert not verify(expected_pub, message + b"\x00", expected_sig)
        print("RFC 8032 §7.4 %-8s ok" % vector["name"])


if __name__ == "__main__":
    _self_check()
    skipped = cross_check_against_core()
    if skipped:
        print("cross-check against otrv4_core skipped: %s" % skipped)
    else:
        print("cross-check against otrv4_core (ed448-goldilocks-plus): ok")
    print("all RFC 8032 Ed448 self-checks passed")
